### ISSUE TITLE
語彙を整理する

### ISSUE THREAD

**Issue by arith-alexander** [mikanmatsuri/mikantaberu#1]
# 課題内容
子供にもわかるような言葉で下記を説明する。
説明をこのissueのコメントに残す。

①それは何？
②それはないと何ができない？

・サーバー
・物理サーバー
・仮想サーバー
・リモート
・ローカル
・AWS
・AWSインスタンス
・バージョン管理システム
・コマンドライン
・コマンド
・コマンドのパラメータ
・github
・git
・リモートリポジトリ
・ローカルリポジトリ
・git add, commit, push, status, pull
・ブラウザー
・ブラウザーのアドレスバー
・プロトコール
・ポート
・ip
・http
・https
・sshプロトコール
・sshコマンド
・ディレクトリ（フォルダ）
・php storm
・ide
・LAMP
・webサーバー
・dbサーバー
・apache
・mysql
・ドキュメントルート
・パーミッション
・キャッシュ
・デプロイ

# 目的
基本語彙の理解度を深めて、忘れないように記録を残す

# 期限
一日以内

**Comment by mikanmatsuri** [comment]
隊長！ありがとうございます！
語彙整理、りょりょまるです！

**Comment by arith-alexander** [comment]
@mikanmatsuri 
私に何か聞くときは@つけてね。
それ以外のコメントは記録として忘れないようにのこしてね。

**Comment by mikanmatsuri** [comment]
@arith-alexander 　はーい！
ところで、サーシャは、マリオのきのこ？

**Comment by arith-alexander** [comment]
@mikanmatsuri 
これ会社のアカウントなのでログインしなおすね

**Comment by mikanmatsuri** [comment]
@arith-alexander 　はい

**Comment by AlexanderKupriyanov** [comment]
@mikanmatsuri 
改めてよろしく！

**Comment by mikanmatsuri** [comment]
@arith-alexander うん！よろしく！

**Comment by mikanmatsuri** [comment]
@arith-alexander Minecraftのキャラ？

**Comment by AlexanderKupriyanov** [comment]
@を間違わないでね

**Comment by AlexanderKupriyanov** [comment]
そう

**Comment by mikanmatsuri** [comment]
@　を、押すと、さっきのやつしか表示されない

**Comment by mikanmatsuri** [comment]
@AlexanderKupriyanov あ、出た！

**Comment by mikanmatsuri** [comment]
サーバー…　PCと似たような機能を持つもの。
これがないと、様々なサービスを受けることが出来ない

**Comment by AlexanderKupriyanov** [comment]
@mikanmatsuri 
そう、そんな感じでいい。

**Comment by AlexanderKupriyanov** [comment]
@mikanmatsuri 
ちなみに普通のｐｃにサーバー用のソフトをインストールして、常に電源ONにすれば、そのｐｃをサーバーと呼ぶことができる。
ただ、普通のPCはサーバーとして扱いにくいので、やっている人が少ない。

サーバーの特徴は、サーバー用のソフトがインストールされていて、電源が常にONになっている。
大体のサーバーはlinuxだけど、windowsのサーバーもある。

**Comment by mikanmatsuri** [comment]
物理サーバ
物理的に存在しているサーバ

仮想サーバ
仮想でつくりだしたサーバ

**Comment by AlexanderKupriyanov** [comment]
一つの物理サーバで専用ソフトをインストールして設定すれば、複数仮想サーバーを作ることができるね。

**Comment by AlexanderKupriyanov** [comment]
詳しくは
https://www.kagoya.jp/howto/rentalserver/virtualization/

**Comment by AlexanderKupriyanov** [comment]
仮想サーバーはバーチャルサーバーとも言う

**Comment by mikanmatsuri** [comment]
リモート
別の場所から作業が行える

**Comment by mikanmatsuri** [comment]
ローカル
ネットワークやサーバーに繋がれてない環境

**Comment by AlexanderKupriyanov** [comment]
大体あっている
リモート　物理的に手元にないもの
ローカル　物理的に手元にあるもの

**Comment by AlexanderKupriyanov** [comment]
ペース早めないと今日中間に合わないよ

**Comment by mikanmatsuri** [comment]
AWS
アマゾンが提供しているWEBサービス

AWSインスタンス
AWSクラウドにある仮想サーバ

バージョン管理システム
ファイルの変更履歴を管理するためのシステム

**Comment by AlexanderKupriyanov** [comment]
おｋ

>クラウド

クラウドとは何と聞きたくなる。
クラウドの定義をまだ教えてないはず。
ま、AWSの仮想サーバであっているよ。

**Comment by mikanmatsuri** [comment]
コマンドライン
キーボードだけで操作する画面上の入力行

コマンド
コンピュータに特定の機能の実行を指示する命令

コマンドのパラメータ
ファイルのパス？みたいな？

**Comment by mikanmatsuri** [comment]
github
ソフトウェア開発で使われるツール

git
プロフラムのソースコードを記録したり、追跡する為のバージョン管理システム

リモートリポジトリ
ネットワークに複数存在する保管場所のこと

ローカルリポジトリ
自分のPC環境だけにある保管場所のこと

git add
ファイルを追加

commit
ファイルを確定させる

push
ファイルを更新する

status
バージョン管理の状態を確認する

pull
他の人が行ったリポジトリの変更点をローカルリポジトリに取り込む

**Comment by AlexanderKupriyanov** [comment]
>コマンドのパラメータ
ファイルのパス？みたいな？

ファイルのパスは例ね。
コマンドの詳細を定義するのがパラメータだ。
例えばｓｓｈコマンドだけ実行しても何も起こらない。
パラメータが必須。
ｓｓｈのパラメータの一つは例えば -i
-i の意味は「プライベートキーを指定する」
-i の次はpandamanへのパスを指定する必要がある

**Comment by AlexanderKupriyanov** [comment]
例えば ｌｓコマンドを実行するとフォルダの中身が出力されるけど、隠されているファイルが表示されない。
隠されているファイルも表示するには -a パラメータが必要
ls -a

**Comment by AlexanderKupriyanov** [comment]
>github
ソフトウェア開発で使われるツール

曖昧過ぎる。
githubはgitのリモートリポジトリを保管するサービスです。

その他の定義は問題ない。

**Comment by mikanmatsuri** [comment]
ブラウザー
google crome、ファイアフォックスみたいな、インターネットをする為のソフト

ブラウザーのアドレスバー
ブラウザが、現在いるWEBページのURLを表示するツールバーのこと

プロトコール
コンピュータネットワークで通信を行う為の手順や約束事

ポート
ネットワークからPCを繋ぐドアとドアのこと。また、機器との接続口

ip
インターネットプロトコルのこと。インターネット上でデータのやり取りをするときに使用する

http
ホームページのファイルのやり取りをするときに使う通信上の約束事

https
SSLを利用したhttp通信

**Comment by mikanmatsuri** [comment]
@AlexanderKupriyanov 
プロトコル
ミッションインポッシブル　ゴーストプロトコル

**Comment by AlexanderKupriyanov** [comment]
>ブラウザー
google crome、ファイアフォックスみたいな、インターネットをする為のソフト

正確に言うと、さまざまなwebプロトコールで渡されるデータをエンドユーザーに表示するためのプログラム。そのプロトコールは大体httpかhttpsだけど、たまにftpとかも使われる。
例：　ftp://ftp.adobe.com/

**Comment by AlexanderKupriyanov** [comment]
ftp://ftp.adobe.com/ をアドレスバーに入れてみて

**Comment by AlexanderKupriyanov** [comment]
>ip
インターネットプロトコルのこと。インターネット上でデータのやり取りをするときに使用する

間違ってはいないけど、ipと言うときは大体ipアドレスという意味。
ipアドレスの定義をしてください。

**Comment by AlexanderKupriyanov** [comment]
>https
SSLを利用したhttp通信

これはまたsslとは何、と聞きたくなる。
ファイルをウェブで渡すときは、送信元のｐｃ（またはサーバー）から宛先のｐｃに届くまで、たくさんのサーバーを通過している。httpプロトコールだとその中間のサーバーにアクセスできる人は通過しているデータすべて見れる。パスワードとかもね。
htpsだとデータが暗号化されるので、中間のサーバーにアクセスできる人は通過しているデータを見れない。
だからhttpsのほうが安全。
githubはhttpsを使っている。
https://github...

**Comment by AlexanderKupriyanov** [comment]
そのほかの定義は問題ない。
分かりやすい例
サーバー　＝　国
プロトコール　＝　空中運送規約、水上運送規約
ポート　＝　空港、港
情報　＝　飛行機、船

飛行機が港で着陸できないのと同じく、httpプロトコールのポート80越しサーバーの操作ができない。
サーバーの操作のためはsshプロトコールのポート22があるので。

**Comment by AlexanderKupriyanov** [comment]
@mikanmatsuri 
もうちょっとで終わるよ！
＼（＞０＜）／　がんば～

**Comment by mikanmatsuri** [comment]
sshプロトコール
リモートサーバに安全にログイン出来たり、ファイルをセキュアに送受信できるもの？

sshコマンド
暗号化された通信を使ってリモート接続するためのコマンド

ディレクトリ（フォルダ）
PC上の、情報を管理するフォルダのこと？

**Comment by AlexanderKupriyanov** [comment]
>sshプロトコール
リモートサーバに安全にログイン出来たり、ファイルをセキュアに送受信できるもの？

サーバーの操作をできるためのプロトコール。
sshコマンドでサーバーに接続して、コマンドラインを使ってサーバーにlsとかcdとかvimとかmkdirとかいろんなコマンドを送って、サーバーの中身を見れて編集できるためのプロトコール。

**Comment by AlexanderKupriyanov** [comment]
>ディレクトリ（フォルダ）
PC上の、情報を管理するフォルダのこと？

そうね。pc上、サーバー上。

**Comment by AlexanderKupriyanov** [comment]
例えばlsコマンドをたたけば、現在いるディレクトリの中にあるファイルとディレクトリ一覧を表示できる。

**Comment by AlexanderKupriyanov** [comment]
mkdirコマンドで新しいディレクトリが作れる。

**Comment by mikanmatsuri** [comment]
php storm
PHPに適した開発環境。これを使えば、PHPのソースコードが見やすくなる。

ide
何か作りたいときは、これ一つで足りるよ!みたいな開発環境のこと。php stormもPHPのideといえる。

LAMP
Linux、Apatch、Mysql、Perl(PHP、Python)、の頭文字をとったもの。この４つの技術を使うことで、WEBが作れますよ!という意味になる

**Comment by AlexanderKupriyanov** [comment]
そうね。

**Comment by AlexanderKupriyanov** [comment]
追記できることもない。

**Comment by AlexanderKupriyanov** [comment]
php stormは他のideと同じく、色んな便利な機能がついている手帳として考えていい。
例えば自動的にデプロイできる機能とか。

**Comment by AlexanderKupriyanov** [comment]
文字に色が自動的について文字が見やすくなる機能とか。

**Comment by AlexanderKupriyanov** [comment]
@mikanmatsuri 
あと８個！

**Comment by AlexanderKupriyanov** [comment]
@mikanmatsuri 
分からない分からないって言ってたのに大体全部わかってるじゃん

**Comment by mikanmatsuri** [comment]
webサーバー
WEBブラウザからのリクエストに応じて画像などを表示するもの？

dbサーバー
データベースが置いてあるコンピュータのこと？

apache
WEBサーバのソフトウェア

mysql
WEBサーバのソフトウェア

ドキュメントルート
WEBサイトなどを利用して外部に後悔するためのデータが設置されたサーバー上のディレクトリのこと？

パーミッション
アクセス権

キャッシュ
お金

デプロイ
ネットワークを通じて提供されるWEBアプリ

**Comment by mikanmatsuri** [comment]
@AlexanderKupriyanov 　今、調べながら書いてるもん

**Comment by AlexanderKupriyanov** [comment]
@mikanmatsuri 
ま、聞くよりは自分で調べて書いたほうが頭に残ると思うよ。
あとで参考できるし。

**Comment by mikanmatsuri** [comment]
@AlexanderKupriyanov Complete？

**Comment by AlexanderKupriyanov** [comment]
>webサーバー
WEBブラウザからのリクエストに応じて画像などを表示するもの？

大体そうね。
ただ、必ずしもブラウザーからではない。
画像ファイル、音声ファイル、htmlファイルとか様々なファイルね。

**Comment by AlexanderKupriyanov** [comment]
正確に言うと、画像を表示するのはブラウザー。
ウェブサーバーはその画像とかのデータをブラウザーのほうに返しているだけ。

**Comment by AlexanderKupriyanov** [comment]
リクエストしてきたPCのほうにサーバーのデータを送り返すサービスを提供しているのはウェブサーバ。

**Comment by AlexanderKupriyanov** [comment]
>dbサーバー
データベースが置いてあるコンピュータのこと？

ちょっと違う。
データベースのファイルがある。
ただ、データベースのファイルだけでは何も動かない。
DBサーバはデータベースを操作できるためのサービスを提供している。
データベースに新規データを入れるためのコマンドをうけつけるのはDBサーバ。
データベースのデータを編集するためのコマンドをうけつけるのもDBサーバ。
データ検索サービスを提供しているのもDBサーバ。
別の課題でそれを詳しく理解できるようになると思うので、今のところはおｋ。

**Comment by AlexanderKupriyanov** [comment]
>ドキュメントルート
WEBサイトなどを利用して外部に後悔するためのデータが設置されたサーバー上のディレクトリのこと？

公開ね。その理解で問題ない。

**Comment by AlexanderKupriyanov** [comment]
>キャッシュ
お金

その意味もあるけど、ITでのキャッシュは
データにより早くアクセスできるために、遠いところにあるデータを一時的に近いところに保存して、その保存したものを優先的に参照する仕組みのことだ。

例えば以前dnsサーバの説明をしたと思う。
それはホスト名（例えばgithub.com）をipアドレス（例えば12.231.162.123）に変換するためのサーバー。ただ、ユーザーがgithub.comにアクセスしているたびに毎回dnsサーバにリクエストが飛ぶわけではない。毎回そんなことしたらサイトが開くのに数秒かかってサイトが遅くなる。
そのためにブラウザーのdnsキャッシュの仕組みがある。
github.comに初めてアクセスするとき一回だけdnsサーバにリクエストが飛んで、その結果がブラウザーのキャッシュに保存される。次にgithub.comにアクセスするときは、ブラウザーに保存されたipを使っている。で、ブラウザーを閉じたら、ブラウザーに保存されたdnsのキャッシュも削除される。
ちなみにdnsはブラウザー側だけではなく、プロバイダー側でもキャッシュされる。

そのようなキャッシュの仕組みはいろいろあるので、別の課題で詳しく調べよう。

**Comment by AlexanderKupriyanov** [comment]
>デプロイ
ネットワークを通じて提供されるWEBアプリ

違うね。

デプロイとはローカルからリモートサーバーにhtmlファイルやphpファイルなどソースコードをアップロードする作業のこと。

例えばローカルで作ったhtmlファイルをサーバーのドキュメントルートにデプロイしたら、
ブラウザーからそのサーバーのipにアクセスするときそのデプロイしたhtmlの中身がブラウザーで表示される。

**Comment by AlexanderKupriyanov** [comment]
@mikanmatsuri 
Completeだね
おめでとう！🎉

**Comment by mikanmatsuri** [comment]
@AlexanderKupriyanov ありがとう(^_-)-☆

**Comment by AlexanderKupriyanov** [comment]
明日の課題もう見た？

**Comment by mikanmatsuri** [comment]
@AlexanderKupriyanov 見た！

**Comment by AlexanderKupriyanov** [comment]
じゃ、次回もよろしく！

**Comment by AlexanderKupriyanov** [comment]
ルートディレクレクトリ　木の根っこ　一番最初のディレクトリ
cd /

**Comment by AlexanderKupriyanov** [comment]
ホームディレクトリ　ユーザー専用ディレクトリ
cd ~
cd /home/Alexander

**Comment by AlexanderKupriyanov** [comment]
木の枝＝ディレクトリ
葉っぱ＝ファイル

**Comment by AlexanderKupriyanov** [comment]
相対パス　今いるディレクトリからのパス
絶対パス　ルートディレクトリからのパス

絶対パスはいつも　/　から始まる

**Comment by AlexanderKupriyanov** [comment]
httpd = apacheのプロセス

yum パッケージインストーラー
ほかのプログラムをインストールするためのプログラム
